# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "about/"
  weight = 10

#[[main]]
#  name = "Research"
#  url = "#projects"
#  weight = 10

[[main]]
  name = "Events"
  url = "#talks"
  weight = 25

[[main]]
  name = "Research"
  url = "#featured"
  weight = 30

[[main]]
  name = "News"
  url = "#posts"
  weight = 40
  
[[main]]
  name = "Education"
  url = "education/"
  weight = 50
  
#[[main]]
#  name = "People"
#  url = "people/"
#  weight = 55

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

#[[main]]
#  name = "Donate"
#  url = "https://giving.cu.edu/fund/biochemistry-and-molecular-genetics-discovery-fund"
#  weight = 70

